"""added has_documents field in ChatSession model

Revision ID: 849677eacf1c
Revises: 981a4b97626e
Create Date: 2025-08-20 15:11:50.490664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '849677eacf1c'
down_revision: Union[str, Sequence[str], None] = '981a4b97626e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('has_documents', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'has_documents')
    # ### end Alembic commands ###
